name: CI/CD

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Package with mvn
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            mbirum/home-services:latest
            mbirum/home-services:${{ github.sha }}

  deploy:
    name: Deploy
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: https://2FFFD13F98E778D55CD5FF3C63114676.gr7.us-east-2.eks.amazonaws.com
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v4
        
      - name: Inject secrets
        run: |
          sed -i "s,SECRET_NEW_RELIC_LICENSE_KEY,${{ secrets.NEW_RELIC_LICENSE_KEY }}," k8s/deployment.yaml

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: services
          manifests: |
            k8s/deployment.yaml
            k8s/ingress.yaml
            k8s/service.yaml
          images: |
            mbirum/home-services:${{ github.sha }}